### ISSUE TITLE
Displaying old events

### ISSUE THREAD

**Issue by hazardousmedic** [sabo10o29/MMM-TimeTreeEvent#5]
I had a calendar event yesterday (working day shift) and no events today, but it is stuck showing the event from yesterday still. I know it is refreshing as I changed it to 3 days ahead and it pulled my next shift 2 days from now, and cleared it when putting it back to 1 day but still displays yesterday's event.

Does this not handle days without events and will always pull the last one instead of a blank day?

**Comment by hazardousmedic** [comment]
In case anyone else has issues - there is a timezone set to "Asia/Tokyo" in MMM-TimeTreeEvent.js that I needed to modify to my own area as it was picking up things at weird times.

**Comment by sabo10o29** [comment]
I apologize for the very late response.
You can change the timezone to overwrite it on config file. I updated readme.
https://github.com/sabo10o29/MMM-TimeTreeEvent/pull/17
