### ISSUE TITLE
request library not loaded

### ISSUE THREAD

**Issue by sdetweil** [sabo10o29/MMM-TimeTreeEvent#9]
in MM 2.16 we removed the request library because it is discontinued (deprecated) 
but this module uses it without listing it in package.json

see https://forum.magicmirror.builders/topic/15778/fix-for-black-screen-in-2-16-and-later

the package.json needs to be updated to avoid this problem for every user

**Comment by sabo10o29** [comment]
The library has been added and will be closed.
